# Generated by Django 2.0.7 on 2018-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screenshots', models.ImageField(upload_to='')),
                ('completion', models.DateField()),
                ('started', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, unique=True)),
                ('profilePicUrl', models.TextField(max_length=60)),
                ('summary', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='resume',
            field=models.ForeignKey(on_delete=False, to='django_rat.Resume'),
        ),
    ]
