# Generated by Django 2.0.3 on 2018-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
