# Generated by Django 2.0.3 on 2018-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rat', '0002_auto_20180703_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='resume',
            field=models.ForeignKey(on_delete=False, to='django_rat.Resume'),
        ),
    ]
