# Generated by Django 2.0.3 on 2018-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rat', '0003_auto_20180703_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='django_rat.Resume'),
        ),
    ]
