# Generated by Django 2.0.3 on 2018-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rat', '0004_auto_20180704_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='resume',
            field=models.ForeignKey(on_delete=False, to='django_rat.Resume'),
        ),
    ]
